### ISSUE TITLE
Doesn't work with AD Oauth2 2.0

### ISSUE THREAD

**Issue by iamlgh** [pplu/azure-ad-auth#4]
I am using ClientCredentials. The application I am connecting to requires that we use v2.0 (token_endpoint => "https://login.microsoftonline.com/$tenant_id/oauth2/v2.0/token"). I can specify this as a parameter to the ClientCredentials call, but I get this error:

> Exception with type: Remote: {"error":"invalid_request","error_description":"AADSTS901002: The 'resource' request parameter is not supported.\r\nTrace ID: 268cc3d4-d9f9-4ea3-82e0-9041bbb50f00\r\nCorrelation ID: 3b7150f3-79c3-4538-8b00-569e26dddcb8\r\nTimestamp: 2022-02-11 08:30:37Z","error_codes":[901002],"timestamp":"2022-02-11 08:30:37Z","trace_id":"268cc3d4-d9f9-4ea3-82e0-9041bbb50f00","correlation_id":"3b7150f3-79c3-4538-8b00-569e26dddcb8"} with HTTP status 400

It works if I send the scope as the resource_id and change the name of the value sent from **resource** to **scope** in this code:

```
    my $auth_response = $self->ua->post_form(
      $self->token_endpoint,
      {
        grant_type    => 'client_credentials',
        client_id     => $self->client_id,
        client_secret => $self->secret_id,
        resource      => $self->resource_id,
      }
    );
```

But then it doesn't work with v1 and I couldn't figure out a nice way to pass either scope or resource_id in order to provide a patch (I have never worked with Moo or Moose before).

**Comment by pplu** [comment]
Since it seems that v2 is a totally different thing that kind of breaks the v1 module, I would suggest you create ClientCrenentialsV2 with the appropiate attributes.

 You should be able to copy ClientCredentials and adapt that code even if you are not familiar with Moo, since you have already kind of done it. I would advise to change the `token_endpoint` to generate the right URL and to change the `has resource` attribute to `has scope` so as to align the terminologies used.

I would gladly accept a contribution like that and publish it to CPAN.

**Comment by iamlgh** [comment]
I made a pull request with the update.

**Comment by pplu** [comment]
Version 0.04 with your changes has just been uploaded to CPAN :)

I have just done some minor changes to link to the V2 module, and specify that it is using the V2 Oauth endpoint. You can take a look in my repos history.

Thank you for your contribution and what seems like your fist contribution to a Perl module :sunglasses:. Welcome to the community.
